### ISSUE TITLE
Planning with PDDL constants: constants not paresed

### ISSUE THREAD

**Issue by MostafaGomaa** [PlanSys2/ros2_planning_system#135]
Dear Authors and Maintainers,

There are some problems regarding parsing and handling of pddl (:constants). I will post them in separate issues since they differ in severity, the complexity of tracing. This is the first and easiest of them.

## Context

Though **PlanSys** infrastructure and **POPF** planner supports defining PDDL constants in the domain.pddl, they are not passed to the parser and consequently not passed to the planer. This causes the planner to complain during checking of `Actions` which use a constant in one of its preconditions/effects.

## Process

1. Create a domain that defines `(:constants )`  and uses a typed constant in any of its Actions preconds/effects (domain_with_consts.pddl)
2. execute `ros2 launch plansys2_bringup plansys2_bringup_launch_monolithic.py model_file:= $PATH_TO_DOMAIN/domain_with_consts.pddl`
3. Errors occurs and a plane can not be generated
4. issuing `get domain` command in a *PlanSys* terminal returns the pddl domain without the constants.

## Expected result

This causes the planner to complain about type errors and not being able to find a plan:

```
[domain_expert_node-1] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[domain_expert_node-1] Error parsing PDDL: $CONSTANT_NAME$ does not name a known token
[domain_expert_node-1] Error parsing PDDL: $CONSTANT_NAME$ does not name a known token
[domain_expert_node-1] -----------------------------------------------------
[domain_expert_node-1] 
[domain_expert_node-1] The supplied domain/problem file appear to violate part of the PDDL
[domain_expert_node-1] language specification.  Specifically:
[domain_expert_node-1] 
[domain_expert_node-1] The planner will continue, but you may wish to fix your files accordingly
[domain_expert_node-1] Type Errors Encountered in Domain File
[domain_expert_node-1] --------------------------------------
[domain_expert_node-1] 
[domain_expert_node-1] Due to type errors in the supplied domain file, the planner
[domain_expert_node-1] has to terminate.  The log of type checking is as follows:
[domain_expert_node-1] 
[domain_expert_node-1] [ERROR] [1623432788.489788873] [domain_expert]: PDDL syntax error: 
[domain_expert_node-1] Warnings encountered when parsing Domain/Problem File
[domain_expert_node-1] 
[domain_expert_node-1] Errors: 0, warnings: 8
[domain_expert_node-1] /tmp///check_domain.pddl: line: 51: Warning: Undeclared symbol: $CONSTAT_NAME$
[domain_expert_node-1] Type-checking drive_to
[domain_expert_node-1] ...action passes type checking.
[domain_expert_node-1] Type-checking $ACTION_NAME$
[domain_expert_node-1] Object with unknown type: $CONSTANT_NAME$
```

## Current result

The issue occurs during configuring of `DomainExpertNode`.
Errors occur during the initialization of the `DomainExpert` (while parsing the pddl domain) https://github.com/IntelligentRoboticsLabs/ros2_planning_system/blob/7dfddb93ae286ad42b371035d3df7aff3ef821b0/plansys2_domain_expert/src/plansys2_domain_expert/DomainExpert.cpp#L40

 Then during the call to the planner to check the parsed `joint_domain`.
 https://github.com/IntelligentRoboticsLabs/ros2_planning_system/blob/7dfddb93ae286ad42b371035d3df7aff3ef821b0/plansys2_domain_expert/src/plansys2_domain_expert/DomainExpertNode.cpp#L126
 
This is due to the fact that the `DomainReader` never extracts the constants from the `domain_str`.
The `joint_domain` is then passed to the planner and checked without the constants.

## Possible Fix

Similarly to what is already done in `DomainReader.cpp` in the processing `domain.pddl` arguments. extract `(:constants)`. Furthermore, include constants string in the returned `get_joint_domain`.

I have already worked on the solution and would be happy to provide a PR for the issue.

**Comment by roveri-marco** [comment]
@fmrico If the support has been added in GH-139 (as it seems from the log above), then you may consider closing this issue.
