### ISSUE TITLE
Throw useful exceptions instead of failing/terminating silently

### ISSUE THREAD

**Issue by MostafaGomaa** [PlanSys2/ros2_planning_system#161]
This is to document places in the code where the program terminates silently instead of throwing a useful exception. This makes it hard to understand what actually happened or to recover in run-time.

This collaborative issue is intended to spark a discussion about:
* Whether this really is an intended behavior
* What's the best way to notify the user
* What's the best way to recover from such run-time issue

Please, feel free to mark code locations where this happens, or to comment!

**Comment by MostafaGomaa** [comment]
https://github.com/IntelligentRoboticsLabs/ros2_planning_system/blob/e713d72a4aa617d5e50439b8afe079d84851e8f2/plansys2_pddl_parser/src/plansys2_pddl_parser/TypeGround.cpp#L28

**Comment by fmrico** [comment]
Hi @MostafaGomaa 

This is clearly a bug or a design error. We should address this soon.

Thanks

**Comment by sarcasticnature** [comment]
I'm currently working on adding/fleshing out failure messages to some stuff, as part of a PR to fix #174.  So far I have implemented a more descriptive failure message to the `ExecutorClient` when actions fail, but be adding some more runtime failure info to a few other places as well.
