### ISSUE TITLE
popf_plan_solver status return

### ISSUE THREAD

**Issue by Splinter1984** [PlanSys2/ros2_planning_system#214]
https://github.com/IntelligentRoboticsLabs/ros2_planning_system/blob/fcd86f60ed37992c8a2bbda04d57dbbfadb84685/plansys2_popf_plan_solver/src/plansys2_popf_plan_solver/popf_plan_solver.cpp#L68

Hi, I noticed that the next call is executed without informing about the status of the process, why not check for the return value?

**Comment by fmrico** [comment]
Hi @Splinter1984 

Yes, this can be improved. Any suggestion? 😉 

Thanks
Francisco
