### ISSUE TITLE
Add option for logging the execution of BTs [feature request]

### ISSUE THREAD

**Issue by sarcasticnature** [PlanSys2/ros2_planning_system#225]
BT.CPP has a [useful logging feature](https://www.behaviortree.dev/tutorial_05_subtrees/) which allows you to save the behavior tree's execution and later play it back using Groot.  It would be nice to have this as an option when running a `bt_action_node`, especially for autonomous robots which cannot be actively monitored during operation.

I am currently working on this feature and will make a pull request soon

**Comment by fmrico** [comment]
It sounds great!! :smiley:
