### ISSUE TITLE
Whether wait_for_result is not required.

### ISSUE THREAD

**Issue by zzsqwq** [PlanSys2/ros2_planning_system#237]
Hello, I was using your code recently and saw that there is a `wait_for_result` function, I would like to know what is the difference between this function and direct future.wait_for(waitTime) , E.g 
````c++
std::shared_futrue fut;
std::chrono::milliseconds wait_period(5000);
auto fut_status_1 = fut.wait_for(wait_period);
// vs
auto fut_status_2 = wait_for_result(fut, wait_period);
````
What is the difference between `fut_status_1` and `fut_status_2`?

https://github.com/PlanSys2/ros2_planning_system/blob/453b5df462d4c606115fc1e286b53e45fda34d67/plansys2_lifecycle_manager/include/plansys2_lifecycle_manager/lifecycle_manager.hpp#L35-L51

**Comment by fmrico** [comment]
At first glance, our version is sensitive to rclcpp::ok() being false. I did this 3 years ago, and I don't remember very well if there was another reason.

**Comment by zzsqwq** [comment]
@fmrico ok i got it, thanks!!!
