### ISSUE TITLE
Help -- PlanSys2 custom planner engine

### ISSUE THREAD

**Issue by antbono** [PlanSys2/ros2_planning_system#264]
Hello everyone!

In the PlanSys2 wiki, it is reported that other solvers than POPF and TFD can be easily added. 
I came across this interesting library 

[http://pddl4j.imag.fr/index.html ](http://pddl4j.imag.fr/index.html)

that let you use different planning algorithms and also create new ones. 
I am curious about the possibility of creating a new PlanSys2 solver plugin starting from this library.
Would it be possible according to you?

Thank you again for your time and consideration.

**Comment by fmrico** [comment]
Hi @antbono 

As I commented by email, it is possible, and I will help you with anything you need for this.

Best
