### ISSUE TITLE
BT Action - client ROS2 Action breaking ConsumeQueue decorator

### ISSUE THREAD

**Issue by robodrome** [PlanSys2/ros2_planning_system#288]
This is my use case:
```xml
<root main_tree_to_execute="MainTree">
        <BehaviorTree ID="MainTree">
                <Sequence name="root_sequence">
                           ...
                          <ConsumeQueue queue="{WaypointsQueue}" popped_item="{Waypoint}">
                                    <Move name="move" waypoint="{Waypoint}" />
                          </ConsumeQueue>
                           ...
                </Sequence>
        </BehaviorTree>
</root>
```

**Setup**
**ConsumeQueue** (BTCPP.v3 decorator) -> **Move** (plansys2::BtActionNode) -> **GoToWaypoint** (Action server on robot/sim)

- `ConsumeQueue` is working, when I just write a `tick()` that prints the Waypoints and returns `SUCCESS` it works fine
- but child BT node `Move` stops when the Action Server `GoToWaypoint` returns `SUCCESS`.
- `ConsumeQueue` keeps running `tick` for remainder of Waypoints, but nothing happens.
- so it only executes one waypoint

**Tried so far**
- add `on_feedback` and threshold
- tried override `on_success`, but that doesn't seem to do anything
- added some logging to `BTAction`

Is there an example on how to use the `ConsumeQueue` decorator?
Am I missing something here?

**Comment by fmrico** [comment]
Hi @robodrome 

Let me check what is going on here :thinking:
