### ISSUE TITLE
erro ament_package.templates  in plansys2_executor

### ISSUE THREAD

**Issue by danilosoba** [PlanSys2/ros2_planning_system#325]
Dear plansy2,

When I run colcon build --symlink-install on ros2-iron and ros2-humble, this error appears.

Does anyone know the reason for this error?

 
eulogiogh@eulogiogh-HP:~/plansys2_ws$ rosdep install -y -r -q --from-paths src --ignore-src --rosdistro humble
#All required rosdeps installed successfully
eulogiogh@eulogiogh-HP:~/plansys2_ws$ colcon build --symlink-install
Starting >>> plansys2_msgs
Starting >>> plansys2_lifecycle_manager
Finished <<< plansys2_lifecycle_manager [1.65s]
Finished <<< plansys2_msgs [4.88s]
Starting >>> plansys2_pddl_parser
Starting >>> plansys2_support_py
Finished <<< plansys2_pddl_parser [0.85s]
Starting >>> plansys2_core
Finished <<< plansys2_core [0.59s]
Starting >>> plansys2_popf_plan_solver
Finished <<< plansys2_support_py [1.45s]
Finished <<< plansys2_popf_plan_solver [0.44s]
Starting >>> plansys2_domain_expert
Finished <<< plansys2_domain_expert [1.21s]
Starting >>> plansys2_problem_expert
Finished <<< plansys2_problem_expert [0.62s]
Starting >>> plansys2_planner
Starting >>> plansys2_tools
Finished <<< plansys2_planner [0.78s]
Starting >>> plansys2_executor
Finished <<< plansys2_tools [0.85s]
--- stderr: plansys2_executor
Traceback (most recent call last):
File
"/home/eulogiogh/ros2_humble/install/ament_cmake_core/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py",
line 21, in <module>
from ament_package.templates import get_environment_hook_template_path
ModuleNotFoundError: No module named 'ament_package'
CMake Error at

/home/eulogiogh/ros2_humble/install/ament_cmake_core/share/ament_cmake_core/cmake/ament_cmake_package_templates-
extras.cmake:41 (message):

execute_process(/usr/bin/python3
/home/eulogiogh/ros2_humble/install/ament_cmake_core/share/ament_cmake_core/cmake/package_templates/templates_2_cmake.py
/home/eulogiogh/plansys2_ws/build/plansys2_executor/ament_cmake_package_templates/templates.cmake)
returned error code 1
Call Stack (most recent call first):
/home/eulogiogh/ros2_humble/install/ament_cmake_core/share/ament_cmake_core/cmake/ament_cmake_coreConfig.cmake:41
(include)
/home/eulogiogh/ros2_humble/install/ament_cmake/share/ament_cmake/cmake/ament_cmake_export_dependencies-extras.cmake:15
(find_package)
/home/eulogiogh/ros2_humble/install/ament_cmake/share/ament_cmake/cmake/ament_cmakeConfig.cmake:41 (include)
CMakeLists.txt:8 (find_package)
---
Failed <<< plansys2_executor [0.48s, exited with code 1]
Summary: 10 packages finished [10.9s]
1 package failed: plansys2_executor
1 package had stderr output:

**Comment by fmrico** [comment]
I think this error is related to the setup of your environment. It is not correctly installed or activated
